// Code generated by goctl. DO NOT EDIT.

export interface LoginRequest {
  code: string;
}

export interface Token {
  name: string;
  symbol: string;
  address: string;
  decimals: number;
  logoURI: string;
  chainId: number;
}

export interface LoginResponse {
  token: string;
  manageable: boolean;
  from?: Token;
  to?: Token;
}

export interface ModifyPresetTokenPairRequest {
  from?: Token;
  to?: Token;
}
