import '@/styles/globals.css';
import '@/styles/fonts.css';
import '@rainbow-me/rainbowkit/styles.css';

import { LayoutProps } from '@/.next/types/app/layout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
